#注册端口
server:
  port: 8761

#服务名称
eureka:
  instance:
    hostname: eureka1
  client:
    #程序是要作为服务端，但是jar中存在eureka-client.jar，所以下面两个要false，否则启动会报错的
    #是否注册到eureka
    register-with-eureka: false
    #是否获取注册信息
    fetch-registry: false
    service-url:
      #defaultZone: http://feifei:123456@localhost:8762/eureka/
      #eureka的服务地址，/eureka是固定的
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/,http://localhost:8764/eureka/
      
#security:
#  basic:
#    enabled: true
#  user:
#    name: feifei
#    password: 123456